# Use an empty array to allow CORS requests in all origins.
# Otherwise specify a list of allowed origins.
# If you comment the line below CORS will not be allowed.
cors = []

# Port to run the app.
# If no port is passed then:
# it will use port 443 if a certificate is passed
# otherwise it will use port 80
port = 8443

# Path to certificate file relative to this file.

assets = "tests"
