# minirps -f config.toml

port = 3001
templates = "templates"
assets = "assets"

[[routes]]
method = "GET"
path = "/"

[routes.response]
body = "{% include 'index.html' %}"
headers = { Content-Type = "text/html" }
