# Use an empty array to allow CORS requests across all origins.
# Otherwise, specify a list of allowed origins.
# Uncomment the line below to enable CORS on all origins.
# cors = []

# Port to run the application.
# If no port is passed, it will use port 3000 by default.
port = 3000

# Path to https certificate files relative to this file.
# If any files are missing, it will use an unencrypted http connection.
cert = "assets/certs/cert.txt"
key = "assets/certs/key.txt"

# Path to the static files folder relative to this file.
# You can comment the line below if you don't want to use this feature.
assets = "assets"

# Minijinja templates folders available for all routes.
# You can comment the line below if you don't want to use this feature.
templates = "templates"

# For this example we will create an interface for starwars data available at:
# https://swapi.dev/

[[routes]]
method = "GET"
path = "/demo"

[routes.response]
body = "{% include 'demo.html' %}"

[routes.response.headers]
Content-Type = "text/html"


[[routes]]
method = "GET"
path = "/films"

[[routes.requests]]
name = "films"
method = "GET"
url = "https://swapi.dev/api/films/"

[routes.response]
body = "{% include 'films.html' %}"

[routes.response.headers]
Content-Type = "text/html"


[[routes]]
method = "GET"
path = "/people"

[[routes.requests]]
name = "people"
method = "GET"
url = "https://swapi.dev/api/people/"

[routes.response]
body = "{% include 'people.html' %}"

[routes.response.headers]
Content-Type = "text/html"


[[routes]]
method = "GET"
path = "/planets"

[[routes.requests]]
name = "planets"
method = "GET"
url = "https://swapi.dev/api/planets/"

[routes.response]
body = "{% include 'planets.html' %}"

[routes.response.headers]
Content-Type = "text/html"


[[routes]]
method = "GET"
path = "/species"

[[routes.requests]]
name = "species"
method = "GET"
url = "https://swapi.dev/api/species/"

[routes.response]
body = "{% include 'species.html' %}"

[routes.response.headers]
Content-Type = "text/html"


[[routes]]
method = "GET"
path = "/starships"

[[routes.requests]]
name = "starships"
method = "GET"
url = "https://swapi.dev/api/starships/"

[routes.response]
body = "{% include 'starships.html' %}"

[routes.response.headers]
Content-Type = "text/html"


[[routes]]
method = "GET"
path = "/vehicles"

[[routes.requests]]
name = "vehicles"
method = "GET"
url = "https://swapi.dev/api/vehicles/"

[routes.response]
body = "{% include 'vehicles.html' %}"

[routes.response.headers]
Content-Type = "text/html"
