# minirps -f config.toml

port = 3002
assets = "assets"
templates = "templates"

[[routes]]
method = "GET"
path = "/"

[[routes.requests]]
name = "elements"
method = "GET"
url = "http://localhost:3002/data.json"

[routes.response]
body = "{% include 'table.html' %}"
headers = { Content-Type = "text/html" }

[[routes]]
method = "GET"
path = "/:element"

[[routes.requests]]
name = "elements"
method = "GET"
url = "http://localhost:3002/data.json"

[routes.response]
body = "{% include 'element.html' %}"
headers = { Content-Type = "text/html" }
