# minirps -f config.toml

port = 3002
assets = "assets"
data = "data"
templates = "templates"

[[routes]]
method = "GET"
path = "/"
template = "table.html"

[[routes]]
method = "GET"
path = "/element/:element"
template = "element.html"

[[routes]]
method = "GET"
path = "/json"
template = "json.html"

[[routes]]
method = "GET"
path = "/toml"
template = "toml.html"
