# minirps -f config.toml

port = 8081
assets = "assets"
data = "data"
templates = "templates"
cors = ["http://localhost:8080"]

[[routes]]
method = "GET"
path = "/"
template = "index.html"

[[routes]]
method = "GET"
path = "/debug"
template = "debug/form.html"

[[routes]]
method = "GET"
path = "/debug/:name"
template = "debug/result.html"

[[routes]]
method = "POST"
path = "/debug/:name"
template = "debug/result.html"

[[routes]]
method = "GET"
path = "/cli"
template = "cli.html"

[[routes]]
method = "POST"
path = "/cli"
template = "cli.html"

[[routes]]
method = "GET"
path = "/chemistry"
template = "chemistry/table.html"

[[routes]]
method = "GET"
path = "/chemistry/:element"
template = "chemistry/element.html"

[[routes]]
method = "GET"
path = "/chemistry/data"
template = "chemistry/data.html"

[[routes]]
method = "GET"
path = "/starwars/:resource"
template = "starwars.html"

[[routes]]
method = "GET"
path = "/notes"
template = "notes/read.html"

[[routes]]
method = "POST"
path = "/notes"
template = "notes/create.html"

[[routes]]
method = "GET"
path = "/notes/:title"
template = "notes/edit.html"

[[routes]]
method = "POST"
path = "/notes/:title"
template = "notes/update.html"

[[routes]]
method = "GET"
path = "/cors"
template = "cors.html"
