# minirps -f config.toml

port = 8081
assets = "assets"
data = "data"
templates = "templates"

[[routes]]
method = "GET"
path = "/"
template = "index.html"

[[routes]]
method = "GET"
path = "/form"
template = "form.html"

[[routes]]
method = "GET"
path = "/debug/:name"
template = "debug.html"

[[routes]]
method = "POST"
path = "/debug/:name"
template = "debug.html"

[[routes]]
method = "GET"
path = "/cli"
template = "cli.html"

[[routes]]
method = "POST"
path = "/cli"
template = "cli.html"

[[routes]]
method = "GET"
path = "/chemistry"
template = "chemistry/table.html"

[[routes]]
method = "GET"
path = "/chemistry/:element"
template = "chemistry/element.html"

[[routes]]
method = "GET"
path = "/chemistry/data"
template = "chemistry/data.html"

[[routes]]
method = "GET"
path = "/starwars/:resource"
template = "starwars.html"
